### ISSUE TITLE
 finding module for package github.com/yakuter/ugin/pkg/logger

### ISSUE THREAD

**Issue by kiddick** [yakuter/ugin#13]
```go mod tidy```

go: finding module for package github.com/yakuter/ugin/pkg/logger
github.com/yakuter/ugin imports
	github.com/yakuter/ugin/pkg/logger: no matching versions for query "latest"

**Comment by yakuter** [comment]
Thank you @kiddick let me check and fix the issue.

**Comment by yakuter** [comment]
Just fixed the issue. Thanks for reporting @kiddick
