### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by vincetse** [yakuter/ugin#3]
Hi @yakuter, I've got a really dumb question: Is this boilerplate buildable?  I'm about to go in and change all the `import`s, but figured I'll ask you first since I'm a Golang newbie.  Thank you!

```
main.go:4:2: cannot find package "ugin/pkg/config" in any of:
	/opt/go/1.15.3/src/ugin/pkg/config (from $GOROOT)
	/home/vagrant/go/src/ugin/pkg/config (from $GOPATH)
main.go:5:2: cannot find package "ugin/pkg/database" in any of:
	/opt/go/1.15.3/src/ugin/pkg/database (from $GOROOT)
	/home/vagrant/go/src/ugin/pkg/database (from $GOPATH)
main.go:6:2: cannot find package "ugin/pkg/router" in any of:
	/opt/go/1.15.3/src/ugin/pkg/router (from $GOROOT)
	/home/vagrant/go/src/ugin/pkg/router (from $GOPATH)
```

**Comment by yakuter** [comment]
Hello @vincetse . I is totally my mistake to not use go mod. Now I updated repo. Can you please pull the latest version anywhere in your computer (outside of GOPATH) and just run

`go run main.go`

**Comment by vincetse** [comment]
Thank you for the super-quick response!  It works great now.  On to building something with ugin.  Thank you for putting this together!
